# Generated by Django 3.1.1 on 2020-09-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('email_id', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('gender', models.IntegerField(max_length=50)),
                ('phone_no', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('user_type', models.IntegerField(max_length=1)),
            ],
        ),
    ]
