# Generated by Django 3.1.1 on 2020-09-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home_Rental_System', '0003_city_country_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('amenities_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.IntegerField()),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.IntegerField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=20)),
                ('rent', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('map1', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('bedroom', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('washroom', models.IntegerField()),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.city')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('property_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review', models.CharField(max_length=200)),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.registration')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.property')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.registration')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.property_type'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('payment_date', models.DateField()),
                ('payment_type', models.CharField(max_length=10)),
                ('status', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.property')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.property'),
        ),
        migrations.CreateModel(
            name='AmenitiesAssing',
            fields=[
                ('amenities_assign_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amenities_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.amenities')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home_Rental_System.property')),
            ],
        ),
    ]
